### ISSUE TITLE
PR 정책에 대해

### ISSUE THREAD

**Issue by apple77y** [FEDevelopers/es6features#16]
이참에 PR을 어떻게 운영할지에 대한 생각을 해봤습니다.

개인적으로는 깃헙에서 새롭게 제공하는 리뷰 기능을 이용하면 좋을 것 같네요.

리뷰어 분들은 diff를 보고 괜찮다 싶으면 approve를, 아니면 댓글 토론 및 request change를 누르면 될 것 같습니다.

리뷰어 모두가 approve인 상태에서 PR 요청자가 merge 버튼을 누르는 방식이 어떨지요.

정리하자면 아래와 같습니다.

1. PR 요청 & 리뷰어 지정
2. 모든 리뷰어의 approve를 기다림
3. 최종 승인 후 직접 머지

**Comment by apple77y** [comment]
#15 에서 처음으로 진행해보겠습니다.

**Comment by pouu69** [comment]
그러시죠. 좋습니다.
@apple77y 주무시죠 잘시간입니당.

**Comment by jeonghwan-kim** [comment]
따라해 보겠습니다.

**Comment by apple77y** [comment]
최근에 생긴 기능이라서 저도 많은 사용 경험이 없네요.
대략적인 사용법은 아래의 링크를 참조하시면 될 것 같습니다.

https://help.github.com/articles/about-pull-request-reviews/

**Comment by pouu69** [comment]
PR 단위는 어떤 기준으로 해야 할까요?

**Comment by apple77y** [comment]
커밋은 챕터 별로 쪼개는 게 좋을 것 같지만, PR은 안 쪼개도 될듯 하네요.
참고로 저는 커밋 메세지를 아래와 같이 작성할 예정입니다.

feat #1 : 이터레이터

개인의 취향에 맞게 작성해도 되며, 꼭 저대로 안 해도 됩니다.

**Comment by apple77y** [comment]
해당 이슈는 닫도록 하겠습니다.
